apiVersion: v1
kind: Service
metadata:
  name: {{ include "content-manager.fullname" . }}-backend
  labels:
    {{- include "content-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  {{- with .Values.service.backend.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.backend.type }}
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.backend.ports.metrics }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "content-manager.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend 