apiVersion: v1
kind: Service
metadata:
  name: {{ include "content-manager.fullname" . }}-frontend
  labels:
    {{- include "content-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  {{- with .Values.service.frontend.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.frontend.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "content-manager.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend 